name: Build and Push Firecrawl Images

on:
  push:
    branches: [ Fahad-deployable ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/u3l1p1m5
  API_REPOSITORY: firecrawl-api
  PLAYWRIGHT_REPOSITORY: firecrawl-playwright-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push API image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/api
        file: ./apps/api/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ env.API_REPOSITORY }}:latest
          ${{ env.ECR_REGISTRY }}/${{ env.API_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Playwright service image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/playwright-service-ts
        file: ./apps/playwright-service-ts/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ env.PLAYWRIGHT_REPOSITORY }}:latest
          ${{ env.ECR_REGISTRY }}/${{ env.PLAYWRIGHT_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image details
      run: |
        echo "✅ Images built and pushed successfully!"
        echo "API Image: ${{ env.ECR_REGISTRY }}/${{ env.API_REPOSITORY }}:latest"
        echo "Playwright Image: ${{ env.ECR_REGISTRY }}/${{ env.PLAYWRIGHT_REPOSITORY }}:latest"
        echo "Commit SHA: ${{ github.sha }}"
